### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL_gpu_shadercross#18]
Not that this is super complicated, but it'd probably be good just to explain which translations are possible and that this is different from SDL_shader_tools.

**Comment by DanielGibson** [comment]
And it should document the SPIRV-Cross dependency, and other dependencies, if any.

**Comment by thatcosmonaut** [comment]
Resolved by https://github.com/libsdl-org/SDL_gpu_shadercross/commit/62e7df2544abd30005d8eefb5a62d2edede0fe41
