### ISSUE TITLE
Expand test.c to be an offline shader cross-compiler/validator

### ISSUE THREAD

**Issue by flibitijibibo** [libsdl-org/SDL_gpu_shadercross#19]
We were thinking about good tests for this, and one thing we wanted to have _anyway_ was an offline translator, for people who don't want to do all the compilation mess online. This wouldn't be _exactly_ the same as calling CreateGPUShader but I bet it's easy enough to split up the stages, and _then_ we can have a validator afterward.

**Comment by thatcosmonaut** [comment]
Resolved by https://github.com/libsdl-org/SDL_gpu_shadercross/commit/62e7df2544abd30005d8eefb5a62d2edede0fe41
