### ISSUE TITLE
CI: Add Steam Linux Runtime (Sniper) Task

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL_gpu_shadercross#34]
Related: https://github.com/libsdl-org/SDL/issues/11357 and https://github.com/libsdl-org/SDL/pull/11359

**Comment by flibitijibibo** [comment]
This can be done after #37 and #38 are done - Sniper may need a different workflow altogether depending on how much it takes to build everything within the SDK.
