### ISSUE TITLE
Missing end } for C++ header files

### ISSUE THREAD

**Issue by Svengali** [libsdl-org/SDL_gpu_shadercross#36]
In the header file [SDL_gpu_shadercross.h](https://github.com/libsdl-org/SDL_gpu_shadercross/blob/master/include/SDL3_gpu_shadercross/SDL_gpu_shadercross.h), theres a missing 

`/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
}
#endif
`

I added it locally, and can submit a PR, but just wanted to point it out

**Comment by flibitijibibo** [comment]
I can merge a PR for this if you have it working locally!
