### ISSUE TITLE
Use linking instead of SDL_LoadObject where possible

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL_gpu_shadercross#44]
We recommend vendoring the dxcompiler dependency, but the SDL_LoadObject calls use strings like "libdxcompiler.so", so if the client doesn't explicitly set LD_LIBRARY_PATH the dlopen calls will search the system libraries instead. Is it bad practice to use a relative path for dlopen? I feel like this is surprising behavior, but I understand if this is an issue for package managers.

**Comment by thatcosmonaut** [comment]
Upon further reflection I'm very confused about why dlopen doesn't seem to be respecting the rpath setting. If we can figure that out then this is non issue.

**Comment by thatcosmonaut** [comment]
Apparently we're also using LoadObject for spirv-cross. That's not really an optional component, we should just link it.

**Comment by thatcosmonaut** [comment]
@madebr Could we trouble you to help us with this build system stuff?

**Comment by madebr** [comment]
Sure, create a pr with the C changes to use a linked spirv-cross library and I'll push the required changes to make the ci happy.
This patch will let the SDL_gpu_shadercross libraries link to a shared spirv-cross-c-shared library.
```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -122,9 +122,12 @@ if(SDLGPUSHADERCROSS_STATIC)
        )
 endif()
 
+find_package(spirv_cross_c_shared REQUIRED)
+
 foreach(target IN LISTS SDL3_gpu_shadercross_targets)
        sdl_add_warning_options(${target} WARNING_AS_ERROR ${SDLGPUSHADERCROSS_WERROR})
        target_compile_features(${target} PRIVATE c_std_99)
+       target_link_libraries(${target} PRIVATE spirv-cross-c-shared)
 endforeach()
 
 if(NOT TARGET SDL3_gpu_shadercross::SDL3_gpu_shadercross)
```
