### ISSUE TITLE
MinGW build is missing standard libs

### ISSUE THREAD

**Issue by thatcosmonaut** [libsdl-org/SDL_gpu_shadercross#54]
We should statically link libgcc and libstdc++ in MinGW builds.

**Comment by thatcosmonaut** [comment]
To clarify, it's libspirv-cross-c-shared that's specifically missing the libs.

**Comment by thatcosmonaut** [comment]
Slight problem... SPIRV-Cross depends on threads, which means that MinGW builds introduce a dependency on libwinpthreads. This is unfortunate. I'm not sure that we can wiggle out of this.

**Comment by thatcosmonaut** [comment]
I think we should probably remove the MinGW build from CI, I don't think there's any point since it has a hard dependency on MinGW libs.

**Comment by madebr** [comment]
GitHub actions is imho primarily for ci. Providing binaries is a second goal.

I think we can fix this by linking with `-static`.
I removed `-static-libgcc` from `CMakeLists.txt` because adding this is a job for the packager.

**Comment by thatcosmonaut** [comment]
Fair enough. There is no static implementation of 64-bit MinGW libwinpthread though, and SPIRV-Cross does `#include <thread>`, so anyone using the binaries will have to ship MinGW's libwinpthread.

**Comment by madebr** [comment]
Try latest main, it should now install dependent runtime.

```
-- Installing: D:/a/SDL_gpu_shadercross/SDL_gpu_shadercross/prefix/bin/libspirv-cross-c-shared.dll
-- Installing: D:/a/SDL_gpu_shadercross/SDL_gpu_shadercross/prefix/bin/libgcc_s_seh-1.dll
-- Installing: D:/a/SDL_gpu_shadercross/SDL_gpu_shadercross/prefix/bin/libstdc++-6.dll
-- Installing: D:/a/SDL_gpu_shadercross/SDL_gpu_shadercross/prefix/bin/libwinpthread-1.dll
-- Installing: D:/a/SDL_gpu_shadercross/SDL_gpu_shadercross/prefix/bin/SDL3.dll
```

**Comment by thatcosmonaut** [comment]
Looks good.
